{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMxjsH/gC8y6rjuS32ZrquL",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/syntheticbeek/bravo-departure-model/blob/main/BRAVO_CASTMATE_DEPATURE.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.preprocessing import LabelEncoder\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "# Build your training dataset\n",
        "data = {\n",
        "    'cast_member': [\n",
        "        'Denise Richards', 'Raquel Leviss', 'Olivia Flowers',\n",
        "        'Taylor Ann Green', 'Kyle Richards',\n",
        "        'Tom Sandoval', 'Austen Kroll', 'Whitney Sudler-Smith'\n",
        "    ],\n",
        "    'show': [\n",
        "        'RHOBH', 'VPR', 'Southern Charm',\n",
        "        'Southern Charm', 'RHOBH',\n",
        "        'VPR', 'Southern Charm', 'Southern Charm'\n",
        "    ],\n",
        "    'trigger_timing': [\n",
        "        'mid', 'late', 'early',\n",
        "        'early', 'early',\n",
        "        'late', 'early', 'mid'\n",
        "    ],\n",
        "    'confirmed': [0, 0, 1, 0, 0, 1, 0, 0],\n",
        "    'cast_reaction': [2, 2, 1, 2, 1, 2, 1, 1],\n",
        "    'betrayal_index': [8, 10, 6.5, 8, 5, 10, 7, 6],\n",
        "    'narrative_equity': [7, 7, 7, 8, 10, 10, 8, 5],\n",
        "    'victim_narrative_index': [8, 8, 7, 9, 8, 1, 1, 3],\n",
        "    'prior_incident': [0, 0, 1, 0, 0, 1, 1, 0],\n",
        "    'gender': [0, 0, 0, 0, 0, 1, 1, 1],\n",
        "    'outcome': [1, 1, 1, 1, 0, 0, 0, 0]\n",
        "}\n",
        "\n",
        "df = pd.DataFrame(data)\n",
        "\n",
        "# Encode trigger timing\n",
        "timing_map = {'early': 0, 'mid': 1, 'late': 2, 'after_filming': 3}\n",
        "df['trigger_timing_encoded'] = df['trigger_timing'].map(timing_map)\n",
        "\n",
        "print(df[['cast_member', 'gender', 'betrayal_index', 'victim_narrative_index', 'outcome']])\n",
        "\n",
        "# Features for training\n",
        "features = ['trigger_timing_encoded', 'confirmed', 'cast_reaction',\n",
        "            'betrayal_index', 'narrative_equity', 'victim_narrative_index',\n",
        "            'prior_incident', 'gender']\n",
        "\n",
        "X_train = df[features]\n",
        "y_train = df['outcome']\n",
        "\n",
        "# Train the model\n",
        "model = LogisticRegression()\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "# Print model weights\n",
        "print(\"\\n--- Variable Weights ---\")\n",
        "weights = pd.DataFrame({\n",
        "    'Variable': features,\n",
        "    'Weight': model.coef_[0]\n",
        "}).sort_values('Weight', ascending=False)\n",
        "print(weights.to_string(index=False))\n",
        "\n",
        "# Amanda and West prediction data\n",
        "test_data = {\n",
        "    'cast_member': ['Amanda', 'West'],\n",
        "    'trigger_timing_encoded': [3, 3],\n",
        "    'confirmed': [0, 0],\n",
        "    'cast_reaction': [2, 2],\n",
        "    'betrayal_index': [10, 6],\n",
        "    'narrative_equity': [10, 8],\n",
        "    'victim_narrative_index': [10, 3],\n",
        "    'prior_incident': [0, 1],\n",
        "    'gender': [0, 1]\n",
        "}\n",
        "\n",
        "test_df = pd.DataFrame(test_data)\n",
        "predictions = model.predict_proba(test_df[features])\n",
        "\n",
        "print(\"\\n--- Predictions ---\")\n",
        "for i, name in enumerate(['Amanda', 'West']):\n",
        "    print(f\"{name} — Exit probability: {predictions[i][1]:.1%}\")\n",
        "\n",
        "# Without victim narrative\n",
        "features_no_victim = ['trigger_timing_encoded', 'confirmed', 'cast_reaction',\n",
        "                      'betrayal_index', 'narrative_equity',\n",
        "                      'prior_incident', 'gender']\n",
        "\n",
        "model_no_victim = LogisticRegression()\n",
        "model_no_victim.fit(df[features_no_victim], df['outcome'])\n",
        "\n",
        "test_no_victim = pd.DataFrame([{\n",
        "    'trigger_timing_encoded': 3,\n",
        "    'confirmed': 0,\n",
        "    'cast_reaction': 2,\n",
        "    'betrayal_index': 10,\n",
        "    'narrative_equity': 10,\n",
        "    'prior_incident': 0,\n",
        "    'gender': 0\n",
        "},\n",
        "{\n",
        "    'trigger_timing_encoded': 3,\n",
        "    'confirmed': 0,\n",
        "    'cast_reaction': 2,\n",
        "    'betrayal_index': 6,\n",
        "    'narrative_equity': 8,\n",
        "    'prior_incident': 1,\n",
        "    'gender': 1\n",
        "}])\n",
        "\n",
        "preds_no_victim = model_no_victim.predict_proba(test_no_victim[features_no_victim])\n",
        "\n",
        "print(\"\\n--- Without Victim Narrative Variable ---\")\n",
        "for i, name in enumerate(['Amanda', 'West']):\n",
        "    print(f\"{name} — Exit probability: {preds_no_victim[i][1]:.1%}\")\n",
        "print(f\"\\nGap without victim narrative: {abs(preds_no_victim[0][1] - preds_no_victim[1][1]):.1%}\")\n",
        "\n",
        "# Without betrayal index\n",
        "features_no_betrayal = ['trigger_timing_encoded', 'confirmed', 'cast_reaction',\n",
        "                        'narrative_equity', 'victim_narrative_index',\n",
        "                        'prior_incident', 'gender']\n",
        "\n",
        "model_no_betrayal = LogisticRegression()\n",
        "model_no_betrayal.fit(df[features_no_betrayal], df['outcome'])\n",
        "\n",
        "test_no_betrayal = pd.DataFrame([{\n",
        "    'trigger_timing_encoded': 3,\n",
        "    'confirmed': 0,\n",
        "    'cast_reaction': 2,\n",
        "    'narrative_equity': 10,\n",
        "    'victim_narrative_index': 10,\n",
        "    'prior_incident': 0,\n",
        "    'gender': 0\n",
        "},\n",
        "{\n",
        "    'trigger_timing_encoded': 3,\n",
        "    'confirmed': 0,\n",
        "    'cast_reaction': 2,\n",
        "    'narrative_equity': 8,\n",
        "    'victim_narrative_index': 3,\n",
        "    'prior_incident': 1,\n",
        "    'gender': 1\n",
        "}])\n",
        "\n",
        "preds_no_betrayal = model_no_betrayal.predict_proba(test_no_betrayal[features_no_betrayal])\n",
        "\n",
        "print(\"\\n--- Without Betrayal Index Variable ---\")\n",
        "for i, name in enumerate(['Amanda', 'West']):\n",
        "    print(f\"{name} — Exit probability: {preds_no_betrayal[i][1]:.1%}\")\n",
        "print(f\"\\nGap without betrayal index: {abs(preds_no_betrayal[0][1] - preds_no_betrayal[1][1]):.1%}\")\n",
        "\n",
        "# Without gender\n",
        "features_no_gender = ['trigger_timing_encoded', 'confirmed', 'cast_reaction',\n",
        "                      'betrayal_index', 'narrative_equity', 'victim_narrative_index',\n",
        "                      'prior_incident']\n",
        "\n",
        "model_no_gender = LogisticRegression()\n",
        "model_no_gender.fit(df[features_no_gender], df['outcome'])\n",
        "\n",
        "test_no_gender = pd.DataFrame([{\n",
        "    'trigger_timing_encoded': 3,\n",
        "    'confirmed': 0,\n",
        "    'cast_reaction': 2,\n",
        "    'betrayal_index': 10,\n",
        "    'narrative_equity': 10,\n",
        "    'victim_narrative_index': 10,\n",
        "    'prior_incident': 0\n",
        "},\n",
        "{\n",
        "    'trigger_timing_encoded': 3,\n",
        "    'confirmed': 0,\n",
        "    'cast_reaction': 2,\n",
        "    'betrayal_index': 6,\n",
        "    'narrative_equity': 8,\n",
        "    'victim_narrative_index': 3,\n",
        "    'prior_incident': 1\n",
        "}])\n",
        "\n",
        "preds_no_gender = model_no_gender.predict_proba(test_no_gender[features_no_gender])\n",
        "\n",
        "print(\"\\n--- Without Gender Variable ---\")\n",
        "for i, name in enumerate(['Amanda', 'West']):\n",
        "    print(f\"{name} — Exit probability: {preds_no_gender[i][1]:.1%}\")\n",
        "print(f\"\\nGap without gender: {abs(preds_no_gender[0][1] - preds_no_gender[1][1]):.1%}\")\n",
        "\n",

}
